var chai = require("chai");
var chaiHttp = require("chai-http");
var app = require("../game-server.js").app;


chai.use(chaiHttp); // Configure Chai.

suite("> Running chai testing on the game-server", function()
{
  //Testing the data generated by the procedural level generation tool. A simple RNG.
    test("Test /data/ endpoint", function()
    {
      chai.request('http://localhost:9000').get("/data").end(function(err, res)
      {
        chai.assert.typeOf(res.text, 'string','/data is a string.');
        chai.assert.lengthOf(res.text,1,'/data has a length of 1.');
        chai.expect(res.text).to.be.oneOf(["0","1","2","3","4","5"]);
      });
    });

  //Testing the highscore generation for all 3 highscores. May fail due to MongoDB connection issues.
    test("Test /highscore1/ endpoint", function()
    {
      chai.request('http://localhost:9000').get("/highscore1").end(function(err, res)
      {
        chai.assert.typeOf(res.text, 'string','/highscore1 is a string.');
        chai.expect(res.text).to.contain("#1");
      });
    });
    test("Test /highscore2/ endpoint", function()
    {
      chai.request('http://localhost:9000').get("/highscore2").end(function(err, res)
      {
        chai.assert.typeOf(res.text, 'string','/highscore1 is a string.');
        chai.expect(res.text).to.contain("#2");
      });
    });
    test("Test /highscore3/ endpoint", function()
    {
      chai.request('http://localhost:9000').get("/highscore3").end(function(err, res)
      {
        chai.assert.equal(res.status, 200);
        chai.assert.typeOf(res.text, 'string','/highscore1 is a string.');
        chai.expect(res.text).to.contain("#3");
      });
    });

  //Testing a player joining the server associates the correct data
    test("Test Player Connecting", function()
    {
      chai.request('http://localhost:9000').post("/testConnect/").set('content-type','application/x-www-form-urlencoded').send({id:"testID"}).end(function(err, res)
      {
        var id = "testID";
        chai.assert.equal(res.status, 200);
        chai.assert.equal(res.body[id].playerId, "testID");
        chai.assert.equal(res.body[id].playerName, "TestName");
        chai.assert.equal(res.body[id].roomCode, "NONE");
      });
    });
});
